import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import Header from "components/Header/Header";
import BackgroundImage from "components/BackgroundImage/BackgroundImage";

import mobileBackgroundImg from "public/background_mobile.png";

import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Speaker Rental in Los Angeles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <BackgroundImage src={mobileBackgroundImg}>
        {children}
        </BackgroundImage>
      </body>
    </html>
  );
}
